homeassistant:
  name: server
  # Location required to calculate the time the sun rises and sets
  latitude: 48.839548
  longitude: 2.395671
  elevation: 36 # Impacts weather/sunrise data (altitude above sea level in meters)
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Paris

zwave:
  network_key: !secret network_key
  usb_path: /dev/ttyACM0

#introduction: # Show links to resources in log and frontend

frontend: # Enables the frontend

config: # Enables configuration UI

http:
  api_password: !secret http
  server_host: 127.0.0.1
  trusted_networks:
    - 127.0.0.1

updater: # Checks for available updates

discovery: # Discover some devices automatically

#conversation: # Allows you to issue voice commands from the frontend in enabled browsers

sun: # Track the sun

# Weather Prediction
#sensor:
#platform: yr

keyboard_remote:
  device_name: 'USB Keyboard'
  type: 'key_down'

automation:
  - alias: VMC Auto-On at Midnight
    trigger:
      platform: time
      at: '23:59:00'
    action:
      - service: switch.turn_on
        entity_id: switch.vmc_switch
  - alias: VMC Auto-Off before Sunset
    trigger:
      platform: sun
      event: sunset
      offset: '-00:30:00'
    condition:
      - condition: time
        before: '18:00:00'
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
    action:
      - service: switch.turn_off
        entity_id: switch.vmc_switch
  - alias: Amplifier Living On
    trigger:
      - platform: mqtt
        topic: 'message'
        payload: 'amplifier living on'
    action:
      - service: shell_command.amp_initialise
      - service: switch.turn_on
        entity_id: switch.vmc_switch
  - alias: Amplifier Living Off
    trigger:
      - platform: mqtt
        topic: 'message'
        payload: 'amplifier living off'
    action:
      - service: shell_command.amp_off
  - alias: Amps Off
    trigger:
      - platform: mqtt
        topic: 'message'
        payload: 'amps off'
    action:
      - service: shell_command.amp_off
  - alias: VMC Off
    trigger:
      platform: event
      event_type: keyboard_remote_command_received
      event_data:
        key_code: 43 # KEY_BACKSLASH
    action:
      - service: switch.turn_off
        entity_id: switch.vmc_switch
  - alias: ABC Radio National MP3
    trigger:
      platform: event
      event_type: keyboard_remote_command_received
      event_data:
        key_code: 0 # ??
    action:
      - service: switch.turn_on
        entity_id: switch.vmc_switch
      - service: shell_command.amp_on
      - service: mqtt.publish
        data:
          topic: 'radio'
          payload: 'ABC Radio National MP3'
  - alias: RFI Monde
    trigger:
      platform: event
      event_type: keyboard_remote_command_received
      event_data:
        key_code: 19 # KEY_R
    action:
      - service: switch.turn_on
        entity_id: switch.vmc_switch
      - service: mqtt.publish
        data:
          topic: 'radio'
          payload: 'RFI Monde'
      - service: shell_command.amp_initialise
  - alias: France Culture
    trigger:
      platform: event
      event_type: keyboard_remote_command_received
      event_data:
        key_code: 46 # KEY_C
    action:
      - service: switch.turn_on
        entity_id: switch.vmc_switch
      - service: mqtt.publish
        data:
          topic: 'radio'
          payload: 'France Culture'
      - service: shell_command.amp_initialise
  - alias: leaving
    trigger:
      platform: event
      event_type: keyboard_remote_command_received
      event_data:
        key_code: 57 # KEY_SPACE
    action:
      - service: mqtt.publish
        data:
          topic: 'message'
          payload: 'leaving'
      - service: shell_command.amp_off
  - alias: Volume Up
    trigger:
      - platform: mqtt
        topic: 'message'
        payload: 'living volume up'
    action:
      service: shell_command.amp_volume_up
  - alias: Volume Down
    trigger:
      - platform: mqtt
        topic: 'message'
        payload: 'living volume down'
    action:
      service: shell_command.amp_volume_down
  - alias: VMC change
    trigger:  # https://home-assistant.io/docs/automation/trigger/
      - platform: state
        entity_id: switch.vmc_switch
        from: 'on'
        to: 'off'
      - platform: state
        entity_id: switch.vmc_switch
        from: 'off'
        to: 'on'
    action:  # https://community.home-assistant.io/t/mqtt-send-switch-state-in-action-automation/30327/9
      - service: mqtt.publish
        data:  # https://github.com/bruhautomation/ESP-MQTT-JSON-Digital-LEDs/blob/master/Example%20Home%20Assistant%20Configuration.yaml
          topic: "server/vmc/switch"  # https://home-assistant.io/docs/mqtt/service/
          #   payload: "ON"
          payload_template: "{{ states('switch.vmc_switch') }}"  # https://github.com/rickybrent/433toMQTTto433_ESP8266/wiki/HomeAssistant-configuration-example


shell_command: # requires restart to reload
  amp_off: 'd=Vol_Down; for i in $d $d $d $d $d $d $d Power_Off; do irsend SEND_ONCE Cambridge_X40A_Amplifier $i; sleep 0.25; done'
  amp_volume_down: 'irsend SEND_ONCE Cambridge_X40A_Amplifier Vol_Down'
  amp_volume_up: 'irsend SEND_ONCE Cambridge_X40A_Amplifier Vol_Up'
  amp_on: 'irsend SEND_ONCE Cambridge_X40A_Amplifier Aux_Phono'
  amp_initialise: 'd=Vol_Down; u=Vol_Up; for i in CD $d $d $d $d $d $d $d $d Aux_Phono $u $u $u $u; do irsend SEND_ONCE Cambridge_X40A_Amplifier $i; sleep 0.25; done'

# https://home-assistant.io/components/mqtt_eventstream/
#mqtt_eventstream:
#  subscribe_topic: slaves/#
#  publish_topic: master/topic
#  publish_eventstream_received: true

mqtt:
  broker: stuartpi3
  client_id: server
  username: skldhf84d
  password: !secret mqtt

#mqtt_statestream:
#  base_topic: server

logger: # https://home-assistant.io/docs/mqtt/logging/
  default: warn
  logs:
    homeassistant.components.mqtt: debug
    homeassistant.components.zwave: warn
    homeassistant.components.websocket_api: warn

# history: # Enables support for tracking state changes over time.
# logbook: # View all events in a logbook

# recorder: # https://home-assistant.io/components/recorder/
#   purge_interval: 1
#   purge_keep_days: 7
#   exclude: # https://home-assistant.io/docs/backend/database/
#     entities:
#       - sensor.vmc_exporting
#       - zwave.vmc
#       - sensor.vmc_interval
#       - sensor.vmc_energy
#       - sensor.vmc_alarm_type
#       - sensor.vmc_interval_2
#       - sensor.vmc_previous_reading_2
#       - sensor.vmc_alarm_level
#       - binary_sensor.vmc_int2
#       - sensor.vmc_previous_reading
#       - sun.sun
