homeassistant:
  # Name of the location where Home Assistant is running
  name: server
  # Location required to calculate the time the sun rises and sets
  latitude: 49.3812
  longitude: 2.3862
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 81
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Paris

zwave:
  network_key: !secret network_key
  usb_path: /dev/ttyACM0

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret http
  server_host: 127.0.0.1
  trusted_networks:
    - 127.0.0.1

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
#sun:

# Weather Prediction
#sensor:
#platform: yr

# Text to speech
#tts:
#platform: google

#lirc:
#media_player:
#- platform: vlc
#arguments: --aout pulseaudio

keyboard_remote:
  device_name: 'USB Keyboard'
  type: 'key_down'

automation:
  - alias: Amplifier Living On
    trigger:
      - platform: mqtt
        topic: 'message'
        payload: 'amplifier living on'
    action:
      - service: shell_command.amp_initialise
  - alias: Amps Off
    trigger:
      - platform: mqtt
        topic: 'message'
        payload: 'amps off'
    action:
      - service: shell_command.amp_off
  - alias: VMC pause
    trigger:
      platform: event
      event_type: keyboard_remote_command_received
      event_data:
        key_code: 43 # KEY_BACKSLASH
    action:
      - service: switch.turn_off
      - delay: '08:00:00'
      - service: switch.turn_on
  - alias: Radio_RFI
    trigger:
      platform: event
      event_type: keyboard_remote_command_received
      event_data:
        key_code: 19 # KEY_R
    action:
      - service: shell_command.amp_on
      - service: mqtt.publish
        data:
          topic: 'message'
          payload: 'radio_RFI'
  - alias: France Culture
    trigger:
      platform: event
      event_type: keyboard_remote_command_received
      event_data:
        key_code: 46 # KEY_C
    action:
      - service: shell_command.amp_on
      - service: mqtt.publish
        data:
          topic: 'radio'
          payload: 'France Culture'
  - alias: leaving
    trigger:
      platform: event
      event_type: keyboard_remote_command_received
      event_data:
        key_code: 57 # KEY_SPACE
    action:
      - service: mqtt.publish
        data:
          topic: 'message'
          payload: 'leaving'
      - service: shell_command.amp_off
  - alias: Volume Down
    trigger:
      platform: event
      event_type: ir_command_received
      event_data:
        button_name: KEY_CHANNELDOWN
    action:
      service: shell_command.hpmini110_volume_down

shell_command:
  amp_off: 'irsend SEND_ONCE Cambridge_X40A_Amplifier Power_Off'
  amp_on: 'irsend SEND_ONCE Cambridge_X40A_Amplifier Aux_Phono'
  amp_initialise: 'irsend SEND_ONCE Cambridge_X40A_Amplifier CD Vol_Down Vol_Down Vol_Down Vol_Down Vol_Down Vol_Down Vol_Down Vol_Down Vol_Down Vol_Down Vol_Down Vol_Down Vol_Down Aux_Phono Vol_Up Vol_Up Vol_Up Vol_Up Vol_Up'

# https://home-assistant.io/components/mqtt_eventstream/
#mqtt_eventstream:
#  subscribe_topic: slaves/#
#  publish_topic: master/topic
  #publish_eventstream_received: true

mqtt:
  broker: stuartpi3
  client_id: server
  username: skldhf84d
  password: !secret mqtt

#mqtt_statestream:
#  base_topic: server

# https://home-assistant.io/docs/mqtt/logging/
logger:
  default: warn
  logs:
    homeassistant.components.mqtt: debug
    homeassistant.components.zwave: warn
