name 'op'
description 'Configure my Raspberry Pi'
version '0.0.1'
license 'GPL-3.0'
maintainer 'Stuart Pook'
chef_version '>= 13.8.7'
maintainer_email 'spam@example.com'
source_url 'https://github.com/stuart12/stuart-system'
issues_url 'https://github.com/stuart12/stuart-system/issues'
supports 'raspbian'
