# home assistant configuration for server in entrance
# Copyright Stuart Pook, 2019 (http://www.pook.it/)
---
homeassistant:
  name: entrance
  # Location required to calculate the time the sun rises and sets
  latitude: 48.839548
  longitude: 2.395671
  elevation: 36 # Impacts weather/sunrise data (altitude above sea level in meters)
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Paris
  auth_providers:
    - type: trusted_networks
      allow_bypass_login: true
      trusted_networks:
        - 127.0.0.1
        - ::1

# https://community.home-assistant.io/t/met-no-platform-magically-appears/124391/2

frontend: # Enables the frontend
config: # Enables configuration UI

#system_health: # ui hangs

#zwave:
# network_key: !secret network_key
# usb_path: /dev/zwave # https://community.home-assistant.io/t/powered-zwave-devices-marked-as-dead/1827/12

#introduction: # Show links to resources in log and frontend

discovery:
  ignore:
    # https://www.home-assistant.io/components/freebox/
    - freebox

#http:
# api_password: !secret http
# server_host: 127.0.0.1
# trusted_networks:
#   - 127.0.0.1

#conversation: # Allows you to issue voice commands from the frontend in enabled browsers

sun: # Track the sun

# Weather Prediction
#sensor:
#platform: yr

#  sudo evtest /dev/input/by-id/usb-04d9_USB_Keyboard-event-kbd
keyboard_remote:
 #device_descriptor: '/dev/input/by-id/usb-04d9_USB_Keyboard-event-kbd'
  device_name: 'USB Keyboard'
  type: 'key_down'

automation:
  - alias: VMC Auto-On at Midnight
    trigger:
      platform: time
      at: '23:59:00'
    action:
      - service: switch.turn_on
        entity_id: switch.vmc_switch
  - alias: VMC Auto-Off before Sunset
    trigger:
      platform: sun
      event: sunset
      offset: '-00:30:00'
    condition:
      - condition: time
        before: '12:00:00'
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
    action:
      - service: switch.turn_off
        entity_id: switch.vmc_switch
  - alias: Amplifier Living On KEY_SLASH
    trigger:
      - platform: event
        event_type: keyboard_remote_command_received
        event_data:
          key_code: 53 # KEY_SLASH
      - platform: mqtt
        topic: 'message'
        payload: 'amplifier living on'
    action:
      - service: script.play
  - alias: Amplifier Living Off
    trigger:
      - platform: mqtt
        topic: 'message'
        payload: 'amplifier living off'
    action:
      - service: shell_command.amp_off
  - alias: Amps Off
    trigger:
      - platform: mqtt
        topic: 'message'
        payload: 'amps off'
    action:
      - service: shell_command.amp_off
  - alias: VMC Off KEY_BACKSLASH
    trigger:
      platform: event
      event_type: keyboard_remote_command_received
      event_data:
        key_code: 43 # KEY_BACKSLASH
    action:
      - service: switch.turn_off
        entity_id: switch.vmc_switch
  - alias: Play Spotify KEY_S
    trigger:
      platform: event
      event_type: keyboard_remote_command_received
      event_data:
        key_code: 31 # KEY_S
    action:
      - service: mqtt.publish
        data:
          topic: 'message'
          payload: 'spotify play'
      - service: script.play
  - alias: France Info KEY_I
    trigger:
      platform: event
      event_type: keyboard_remote_command_received
      event_data:
        key_code: 23 # KEY_I
    action:
      - service: mqtt.publish
        data:
          topic: 'radio'
          payload: 'France Info'
  - alias: ABC Radio National MP3 KEY_A
    trigger:
      platform: event
      event_type: keyboard_remote_command_received
      event_data:
        key_code: 30 # KEY_A
    action:
      - service: mqtt.publish
        data:
          topic: 'radio'
          payload: 'ABC Radio National MP3'
  - alias: BBC World Service KEY_B
    trigger:
      platform: event
      event_type: keyboard_remote_command_received
      event_data:
        key_code: 48 # KEY_B
    action:
      - service: mqtt.publish
        data:
          topic: 'radio'
          payload: 'BBC World Service (AAC)'
      - service: script.play
  - alias: RFI Monde KEY_R
    trigger:
      platform: event
      event_type: keyboard_remote_command_received
      event_data:
        key_code: 19 # KEY_R
    action:
      - service: mqtt.publish
        data:
          topic: 'radio'
          payload: 'RFI Monde'
      - service: script.play
  - alias: France Culture KEY_C
    trigger:
      platform: event
      event_type: keyboard_remote_command_received
      event_data:
        key_code: 46 # KEY_C
    action:
      - service: mqtt.publish
        data:
          topic: 'radio'
          payload: 'France Culture'
      - service: script.play
  - alias: Play Podcast KEY_P
    trigger:
      platform: event
      event_type: keyboard_remote_command_received
      event_data:
        key_code: 25 # KEY_P
    action:
      - service: mqtt.publish
        data:
          topic: 'message'
          payload: 'playnewestpod'
      - service: script.play
  - alias: leaving KEY_SPACE
    trigger:
      platform: event
      event_type: keyboard_remote_command_received
      event_data:
        key_code: 57 # KEY_SPACE
    action:
      - service: mqtt.publish
        data:
          topic: 'message'
          payload: 'leaving'
      - service: shell_command.amp_off
  - alias: Volume Up KEY_DOT
    trigger:
      - platform: event
        event_type: keyboard_remote_command_received
        event_data:
          key_code: 52 # KEY_DOT
      - platform: mqtt
        topic: 'message'
        payload: 'living volume up'
    action:
      service: shell_command.amp_volume_up
  - alias: Volume Down KEY_COMMA
    trigger:
      - platform: event
        event_type: keyboard_remote_command_received
        event_data:
          key_code: 51 # KEY_COMMA
      - platform: mqtt
        topic: 'message'
        payload: 'living volume down'
    action:
      service: shell_command.amp_volume_down
  - alias: VMC change
    trigger:  # https://home-assistant.io/docs/automation/trigger/
      - platform: state
        entity_id: switch.vmc_switch
        from: 'on'
        to: 'off'
      - platform: state
        entity_id: switch.vmc_switch
        from: 'off'
        to: 'on'
    action:  # https://community.home-assistant.io/t/mqtt-send-switch-state-in-action-automation/30327/9
      - service: mqtt.publish
        data:  # https://github.com/bruhautomation/ESP-MQTT-JSON-Digital-LEDs/blob/master/Example%20Home%20Assistant%20Configuration.yaml
          retain: true
          topic: "server/vmc/switch"  # https://home-assistant.io/docs/mqtt/service/
          #   payload: "ON"
          payload_template: "{{ states('switch.vmc_switch') }}"  # https://github.com/rickybrent/433toMQTTto433_ESP8266/wiki/HomeAssistant-configuration-example


shell_command: # requires restart to reload
# https://www.mess.org/2019/03/05/How-to-add-support-for-a-new-remote-using-lircd-conf-file/
  amp_off: 'ir-ctl --emitters=3 --scancode rc5:0x100f'
  amp_volume_down: 'ir-ctl --emitters=3 --scancode rc5:0x1011'
  amp_volume_up: 'ir-ctl --emitters=3 --scancode rc5:0x1010'
  amp_on: 'ir-ctl --emitters=3 --scancode rc5:0x1004'
  amp_initialise: 'ir-ctl --emitters=3 -S rc5:0x1005 && sleep 1 && ir-ctl --emitters=3 -S rc5:0x1011 -S rc5:0x1011 -S rc5:0x1011 -S rc5:0x1011 -S rc5:0x1011 -S rc5:0x1011 -S rc5:0x1011 -S rc5:0x1011 -S rc5:0x1011 -S rc5:0x1011 -S rc5:0x1011 -S rc5:0x1011 -S rc5:0x1011 -S rc5:0x1011 -S rc5:0x1011 -S rc5:0x1011 -S rc5:0x1011 -S rc5:0x1011 -S rc5:0x1011 -S rc5:0x1011 -S rc5:0x1011 -S rc5:0x1011 -S rc5:0x1011 -S rc5:0x1011 -S rc5:0x1011 -S rc5:0x1011 -S rc5:0x1011 -S rc5:0x1011 -S rc5:0x1011 -S rc5:0x1011 -S rc5:0x1011 -S rc5:0x1004 -S rc5:0x1010 -S rc5:0x1010 -S rc5:0x1010 -S rc5:0x1010 -S rc5:0x1010 -S rc5:0x1010'

script:
  play:
    sequence:
      - service: shell_command.amp_initialise
      - service: switch.turn_on
        entity_id: switch.vmc_switch

# https://home-assistant.io/components/mqtt_eventstream/
#mqtt_eventstream:
#  subscribe_topic: slaves/#
#  publish_topic: master/topic
#  publish_eventstream_received: true

mqtt:
  broker: bedroom
  client_id: entrance
  username: skldhf84d
  password: !secret mqtt

#mqtt_statestream:
#  base_topic: server

logger: # https://home-assistant.io/docs/mqtt/logging/
  default: info
  logs:
    homeassistant.components.mqtt: info
    homeassistant.components.keyboard_remote: debug
    homeassistant.components.zwave: warn
    homeassistant.components.websocket_api: warn
    homeassistant.setup: info # log during boot
    homeassistant.util.package: info # log during boot
    homeassistant.components.discovery: info # log during boot
    homeassistant.loader: info # log during boot

# history: # Enables support for tracking state changes over time.
# logbook: # View all events in a logbook

# recorder: # https://home-assistant.io/components/recorder/
#   purge_interval: 1
#   purge_keep_days: 7
#   exclude: # https://home-assistant.io/docs/backend/database/
#     entities:
#       - sensor.vmc_exporting
#       - zwave.vmc
#       - sensor.vmc_interval
#       - sensor.vmc_energy
#       - sensor.vmc_alarm_type
#       - sensor.vmc_interval_2
#       - sensor.vmc_previous_reading_2
#       - sensor.vmc_alarm_level
#       - binary_sensor.vmc_int2
#       - sensor.vmc_previous_reading
#       - sun.sun
