homeassistant:
  # Name of the location where Home Assistant is running
  name: master
  # Location required to calculate the time the sun rises and sets
  latitude: 49.3812
  longitude: 2.3862
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 81
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Paris

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
#sun:

# Weather Prediction
#sensor:
#platform: yr

# Text to speech
#tts:
#platform: google

group: !include groups.yaml

lirc:

automation:
  - alias: mute
    trigger:
      platform: event
      event_type: ir_command_received
      event_data:
        button_name: KEY_POWER
    action:
      service: shell_command.mute
  - alias: France Culture
    trigger:
      platform: event
      event_type: ir_command_received
      event_data:
        button_name: KEY_UP
    action:
      service: shell_command.france_culture
  - alias: RFI
    trigger:
      platform: event
      event_type: ir_command_received
      event_data:
        button_name: KEY_OK
    action:
      service: shell_command.rfi
  - alias: Volume Down
    trigger:
      platform: event
      event_type: ir_command_received
      event_data:
        button_name: KEY_CHANNELDOWN
    action:
      service: shell_command.hpmini110_volume_down
  - alias: Volume Up
    trigger:
      platform: event
      event_type: ir_command_received
      event_data:
        button_name: KEY_CHANNELUP
    action:
      service: shell_command.hpmini110_volume_up

shell_command:
  hpmini110_volume_up: 'amixer -c 0 set Master 8%+'
  hpmini110_volume_down: 'amixer -q -c 0 set Master 8%-'
  rfi: 'mute --on; rfi'
  mute: 'mute'
  france_culture: 'ha-radio-browser "France Culture"'

# https://home-assistant.io/components/mqtt_eventstream/
mqtt_eventstream:
  publish_topic: master/topic
  subscribe_topic: slaves/#

# use the builtin broker
mqtt: !include mqtt.yaml
#  username: secret
#  password: very-secret
