include_recipe '::attribute_driven'
include_recipe '::raspbian'
include_recipe '::firewall'
include_recipe '::sshd'
include_recipe '::wifi'
include_recipe '::i2c'
include_recipe '::homeassistant'
include_recipe '::snapclient'
