include_recipe '::raspbian'
include_recipe '::firewall'
include_recipe '::wifi'
include_recipe '::i2c'
include_recipe '::mqtt'
include_recipe '::homeassistant'
include_recipe '::snapclient'
include_recipe '::delcom_clock'
