homeassistant:
  # Name of the location where Home Assistant is running
  name: bedroom
  # Location required to calculate the time the sun rises and sets
  latitude: 49.3812
  longitude: 2.3862
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 81
  unit_system: metric
  time_zone: Europe/Paris

# Enables the frontend
#frontend:
# Enables configuration UI
#config:

http:
  api_password: !secret http
  server_host: 127.0.0.1


lirc:

# https://home-assistant.io/components/mqtt_eventstream/
mqtt_eventstream:
  publish_topic: slaves/bedroom
  subscribe_topic: master/kooka

mqtt:
  username: skldhf84d
  password: !secret mqtt
  broker: kooka
  client_id: stuartpi3

# https://home-assistant.io/components/keyboard_remote/
keyboard_remote:
  device_name: 'ORTEK USB Keyboard Hub'
  type: 'key_down'

automation:
  - alias: Wakeup
    trigger:
        platform: time
        hours: 8
        minutes: 10
        seconds: 0
    action:
      service: shell_command.led_on
    condition:
      condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  - alias: Blink
    trigger:
      platform: event
      event_type: ir_command_received
    action:
      service: shell_command.blink
  - alias: Alarm Stop
    trigger:
      platform: event
      event_type: ir_command_received
      event_data:
        button_name: KEY_TEXT
    action:
      service: shell_command.alarm_stop
  - alias: Swap
    trigger:
      platform: event
      event_type: ir_command_received
      event_data:
        button_name: KEY_CLEAR
    action:
      service: shell_command.swap
  - alias: Sleep
    trigger:
      platform: event
      event_type: ir_command_received
      event_data:
        button_name: KEY_ENTER
    action:
      service: shell_command.sleep
  - alias: Volume Down
    trigger:
      platform: event
      event_type: ir_command_received
      event_data:
        button_name: KEY_VOLUMEDOWN
    action:
      service: shell_command.volume_down
  - alias: Volume Up
    trigger:
      platform: event
      event_type: ir_command_received
      event_data:
        button_name: KEY_VOLUMEUP
    action:
      service: shell_command.volume_up
  - alias: Swap LED status
    trigger:
      platform: event
      event_type: keyboard_remote_command_received
      event_data:
        key_code: 110 # "0" without numlock
    action:
      service: shell_command.swap
  - alias: Play RFI
    trigger:
      platform: event
      event_type: keyboard_remote_command_received
      event_data:
        key_code: 111 # "." without numlock
    action:
      service: mqtt.publish
      data:
        topic: "slaves/bedroom"
        payload: "RFI"

shell_command:
  volume_up: 'amixer -q -c 1 set Speaker 8%+ &'
  volume_down: 'amixer -c 1 set Speaker 8%- &'
  sleep: '2sleep &'
  swap: 'delcom-control --swap &'
  alarm_stop: 'alarm-stop &'
  blink: 'delcom-control --blink &'
  led_on: 'delcom-control --on &'
