homeassistant:
  # Name of the location where Home Assistant is running
  name: bedroom
  # Location required to calculate the time the sun rises and sets
  latitude: 49.3812
  longitude: 2.3862
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 81
  unit_system: metric
  time_zone: Europe/Paris

# Enables the frontend
frontend:
# Enables configuration UI
#config:

http:
  api_password: !secret http
  server_host: 127.0.0.1
  trusted_networks:
    - 127.0.0.1

lirc:

# https://home-assistant.io/components/mqtt_eventstream/
#mqtt_eventstream:
  #publish_topic: slaves/bedroom
  #subscribe_topic: master/kooka

# https://home-assistant.io/components/mqtt_statestream/
#mqtt_statestream:
#  base_topic: bedroom

light:
  - platform: blinksticklight
    serial: BS015348-3.0
    name: bedroom

mqtt:
  username: skldhf84d
  password: !secret mqtt
  broker: localhost
  client_id: stuartpi3
  protocol: 3.1.1

# sudo evtest /dev/input/event1
keyboard_remote:
  device_name: 'ORTEK USB Keyboard Hub'
  type: 'key_down'

automation:
  - alias: Wakeup
    trigger:
        platform: time
        hours: 8
        minutes: 5
        seconds: 0
    action:
      - service: switch.turn_on
        entity_id: switch.delcom_clock
      - service: light.turn_on
        data:
          entity_id: light.bedroom
          brightness_pct: 100
      - delay: '01:00:00'
      - service: light.turn_off
        data:
          entity_id: light.bedroom
      - delay: '00:00:30'
      - service: light.turn_off
        data:
          entity_id: light.bedroom
    condition:
      condition: and
      conditions:
        - condition: time
          weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
        - condition: template
          value_template: '{{ is_state("switch.delcom_clock", "off") }}'
  - alias: Blink
    trigger:
      platform: event
      event_type: ir_command_received
    action:
      service: switch.turn_toggle
      entity_id: switch.delcom_clock
  - alias: RFI Monde
    trigger:
      platform: event
      event_type: keyboard_remote_command_received
      event_data:
        key_code: 107 # "1" without numlock
    action:
      service: mqtt.publish
      data:
        topic: 'message'
        payload: 'radio_RFI'
  - alias: Amplifier Living On
    trigger:
      platform: event
      event_type: keyboard_remote_command_received
      event_data:
        key_code: 55 # "KEY_KPASTERISK" without numlock
    action:
      - service: mqtt.publish
        data:
          topic: 'message'
          payload: 'amplifier living on'
  - alias: Sleep
    trigger:
      platform: event
      event_type: keyboard_remote_command_received
      event_data:
        key_code: 14 # "KEY_BACKSPACE" without numlock
    action:
      - service: switch.turn_off
      - service: mqtt.publish
        data:
          topic: 'message'
          payload: 'amps off'
  - alias: Swap clock status
    trigger:
      platform: event
      event_type: keyboard_remote_command_received
      event_data:
        key_code: 110 # "0" without numlock
    action:
      service: script.toggle_clock
  - alias: Toggle LED red
    trigger:
      platform: event
      event_type: keyboard_remote_command_received
      event_data:
        key_code: 28 # return without numlock
    action:
      - service: script.toggle_bedside_red

  - alias: Toggle LED White
    trigger:
      platform: event
      event_type: keyboard_remote_command_received
      event_data:
        key_code: 111 # "." without numlock
    action:
      - service: script.toggle_bedside_white

switch:
  platform: command_line
  switches:
    delcom_clock:
      command_on: 'delcom-control --on; sleep 1'
      command_off: 'delcom-control --off; sleep 1'
      command_state: 'cat /sys/bus/usb/drivers/usbsevseg/*/text'
      value_template: '{{ value != "\0" }}'
      friendly_name: Bedroom Led

shell_command:
  volume_up: 'amixer -q -c 1 set Speaker 8%+ &'
  volume_down: 'amixer -c 1 set Speaker 8%- &'
  sleep: '2sleep &'
  swap: 'delcom-control --swap &'
  alarm_stop: 'alarm-stop &'
  blink: 'delcom-control --blink &'
  led_on: 'delcom-control --on &'


# https://home-assistant.io/docs/mqtt/logging/
logger:
  default: info
  logs:
    homeassistant.components.mqtt: debug

# https://community.home-assistant.io/t/toggle-a-hue-go-for-a-specific-color-or-scene/11449/4
script:
  toggle_clock:
    sequence:
    - service_template: switch.turn_{% if is_state('switch.delcom_clock', 'off') %}on{% else %}off{% endif %}

  toggle_bedside_red:
    sequence:
    - service_template: script.bedside_{% if is_state('light.bedroom', 'off') %}red{% else %}off{% endif %}

  toggle_bedside_white:
    sequence:
    - service_template: script.bedside_{% if is_state('light.bedroom', 'off') %}white{% else %}off{% endif %}

  bedside_red:
    sequence:
    - service: light.turn_on
      entity_id: light.bedroom
      data:
        color_name: red
        brightness_pct: 100

  bedside_white:
    sequence:
    - service: light.turn_on
      entity_id: light.bedroom
      data:
        color_name: white
        brightness_pct: 100

  bedside_off:
    sequence:
    - service: light.turn_off
      entity_id: light.bedroom
    - delay: '00:00:01'
    - service: light.turn_off
      entity_id: light.bedroom
