homeassistant:
  # Name of the location where Home Assistant is running
  name: bedroom
  # Location required to calculate the time the sun rises and sets
  latitude: 49.3812
  longitude: 2.3862
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 81
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Paris

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http: !include http.yaml

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
#sun:

# Weather Prediction
#sensor:
  #platform: yr

# Text to speech
#tts:
  #platform: google

group: !include groups.yaml

lirc:

automation:
  - alias: Blink
    trigger:
      platform: event
      event_type: ir_command_received
    action:
      service: shell_command.blink
  - alias: Alarm Stop
    trigger:
      platform: event
      event_type: ir_command_received
      event_data:
        button_name: KEY_TEXT
    action:
      service: shell_command.alarm_stop
  - alias: Swap
    trigger:
      platform: event
      event_type: ir_command_received
      event_data:
        button_name: KEY_CLEAR
    action:
      service: shell_command.swap
  - alias: Sleep
    trigger:
      platform: event
      event_type: ir_command_received
      event_data:
        button_name: KEY_ENTER
    action:
      service: shell_command.sleep
  - alias: Volume Down
    trigger:
      platform: event
      event_type: ir_command_received
      event_data:
        button_name: KEY_VOLUMEDOWN
    action:
      service: shell_command.volume_down
  - alias: Volume Up
    trigger:
      platform: event
      event_type: ir_command_received
      event_data:
        button_name: KEY_VOLUMEUP
    action:
      service: shell_command.volume_up

shell_command:
  volume_up: 'delcom-control --blink & amixer -q -c 1 set Speaker 8%+'
  volume_down: 'delcom-control --blink & amixer -c 1 set Speaker 8%-'
  sleep: 'delcom-control --blink & 2sleep &'
  swap: 'delcom-control --swap &'
  alarm_stop: 'delcom-control --blink & alarm-stop &'
  blink: 'delcom-control --blink'

# https://home-assistant.io/components/mqtt_eventstream/
mqtt_eventstream:
  publish_topic: slaves/bedroom
  subscribe_topic: master/topic

mqtt: !include mqtt.yaml
