Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: 'comma'
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: 'comma'
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: 'comma'
Metrics/LineLength:
  Max: 128
Style/FrozenStringLiteralComment:
  EnforcedStyle: 'never'
