#!/bin/sh
# to bootstrap do
# g=github.com; sudo apt update && sudo apt install -y git && mkdir $g && ln -s $g/stuart-system/chef && cd $g && git clone https://$g/stuart12/stuart-system.git && stuart-system/chef/converge
# then create a attributes/5xxxx.rb file for your uuid and hostname etc
set -e
chef=/usr/bin/chef-solo
if [ `id -u` -eq 0 ]; then
	su=
else
	su=sudo
fi
[ -x $chef ] || { $su apt update && $su apt install -y chef; }
PWD=$(dirname $(readlink -f $0))
cd $PWD
recipes=""
for i
do
	recipes="${recipes},recipe[op::$i]"
done
if [ ! -r $PWD/roles/secrets.rb ]; then
	echo "name 'secrets'" > $PWD/roles/secrets.rb
fi
dirty=$(cd $PWD && git status -s | sed -ne '/^R[ M]/s/ .* -> / /' -e 's/...//' -e '/\.rb$/p')
rubocop=/usr/bin/rubocop
if [ -x $rubocop -a -n "$dirty" ]; then
	rcfg=.rubocop-$($rubocop --version | sed --regexp-extended -e 's/([0-9]+)\.([0-9]+).*/\1.\2/').yml
	$rubocop --config $rcfg --auto-correct $dirty
fi
$su $chef --config $PWD/solo.rb --json-attributes $PWD/solo.json ${recipes:+-o role[secrets],role[quick]$recipes}

# chef-shell --solo -z --config $PWD/solo.rb --json-attributes $PWD/solo.json
