#!/bin/sh -e
chef=/usr/bin/chef-solo
[ -x $chef ] || sudo apt install -y chef
DIR=$(dirname $(readlink -f $0))
recipes=""
for i
do
	recipes="${recipes:+$recipes,}recipe[op::$i]"
done
sudo $chef --config $DIR/solo.rb --json-attributes $DIR/solo.json ${recipes:+-o $recipes}
if [ -z "$*" ]; then
	foodcritic $DIR/cookbooks
	rubocop --auto-correct $DIR
fi

# chef-shell --solo -z --config $PWD/solo.rb --json-attributes $PWD/solo.json
